baseURL: /
languageCode: en-ca
title: "Varun Patel"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts


# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1


# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
# DefaultContentLanguage: fr

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Custom parameters
params:
  # background image of the landing page
  background: /images/background.png

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /images/site/logo.svg
    inverted: /images/site/logo.svg
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/varun-patel/varunpatel.ca
  gitBranch: main

  # Configure various features of this theme
  features:

    # Enable dark theme
    darkMode:
      enable: true

    # Enable and configure portfolio
    portfolio:
      enable: true

    # Enable and configure blog posts
    blog:
      enable: false

    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false

    # Enable Analytics
    analytics:
      enabled: true
      services:
        # Google Analytics
        google:
          id: UA-148918898-1

    # Enable Support
    support:
      enable: false

    # Specify whether to show flag in the language selector. Default is true.
    flags:
      enable: true
      # If you want to use different country flag for a language, specify them here.
      flagOverwrites:
        - languageCode: en
          countryCode: ca

    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: false

    # Enable this to create flowcharts using shortcodes.
    flowchart:
      enable: false

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: false

    # Enable to use custom syntax highlight
    # Please note, Hugo comes with it's own html based syntax highlighter.
    # Your code block will still be syntax highlighted by hugo.
    # For more details: https://gohugo.io/content-management/syntax-highlighting/
    # To disable Hugo's builtin syntax highlight,
    # see: https://gohugo.io/getting-started/configuration-markup#highlight
    # ```
    # # config.yaml
    # markup:
    #   # this disables hugo's syntax highlighting.
    #   codeFences: false
    # ```
    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i

    # Enable to use `video-player` shortcode
    videoPlayer:
      enable: false
    
    # Enable reading time support in post cards and in post pages
    readingTime:
      enable: false
    
    # Number of posts to show to each page. Default is "12"
    pagination:
       maxPostsPerPage: 12


  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: false
